### ISSUE TITLE
no pagination links

### ISSUE THREAD

**Issue by zoran** [jsonapi-suite/jsonapi_suite#3]
since the version 0.2.0 pagination links are not rendered anymore. Is this intended?

**Comment by VinceBassman** [comment]
Same diagnosis... It would be create if this could be fixed in the next release... Thanks for the great Job!

**Comment by richmolj** [comment]
@zoran @VinceBassman the 0.2 release was when we switched from using ActiveModelSerializers under the hood to [jsonapi-rb](http://jsonapi-rb.org). Thanks to @beauby's hard work the underlying code is more performant and simpler, but it doesn't support pagination links.

I think we should add these links if they make sense, but I'd like to better understand the use case. I actually dislike these links since they implicitly fire another query (to get the total count of records). In addition, I usually end up needing the information within those links parsed out, anyway (to show the total count of records above a grid, for instance).

I do pagination using the `stats` functionality:

```
GET /posts?stats[total]=count&page[number]=2&page[size]=10
```

This seems to be a better, more explicit pattern to me. But if I can better understand the use case for links, we can see if the suite of jsonapi-rb can support them in the next release.

**Comment by zoran** [comment]
OK, neither me nor @VinceBassman (I talked to him) need the pagination links. We just thought that there is a bug.  Please close the issue.

Thank you and @beauby for sharing your jsonapi gems!

**Comment by richmolj** [comment]
Thanks, @zoran!
