### ISSUE TITLE
Camelcasing and snakecasing params?

### ISSUE THREAD

**Issue by Aryk** [jsonapi-suite/jsonapi_suite#7]
Is this possible to do. So lets say, coming into the app I want the attributes names to go from camel to snake and then on serialize to go back to camel. Is this doable?

**Comment by richmolj** [comment]
Hi @Aryk - for serialization we use [jsonapi-rb](jsonapi-rb.org), so I believe you'd do something like

```ruby
require "jsonapi/serializable/resource/key_transform"

class SerializableResource < JSONAPI::Serializable::Resource
  prepend JSONAPI::Serializable::Resource::KeyTransform
  self.key_transform = -> (key) { key.to_s.camelize :lower }
end
```

Now *incoming* this is not currently a feature - though you could certainly add your own `before_action` and do it yourself. Otherwise if you are looking to PR, you could check out https://github.com/jsonapi-suite/jsonapi_compliable/blob/master/lib/jsonapi_compliable/deserializable.rb#L76

**Comment by richmolj** [comment]
@Aryk is this still an issue for you?

**Comment by Aryk** [comment]
no, not really, i added a before action and I'm doing it myself.
